### ISSUE TITLE
Add `should` to globals

### ISSUE THREAD

**Issue by ricardogama** [seegno/eslint-config-seegno#8]
What do you think about adding `should` as global?

**Comment by ruiquelhas** [comment]
I don't think it is a good idea, since you might need something like:

```js
let foo;
should.not.exist(foo);
```

Which only works if you require `should` explicitly. Of course the issue will also get caught by running the tests but I would argue this would work more like a convenience layer (for instance, if you like to run the tests remotely).

**Comment by fixe** [comment]
@ricardogama you can add the exception locally.
